module.exports.JWT_OPTIONS = {
  ADMIN_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "ADD_RESCUE",
    "ADD_PET",
    "DELETE_ADOPTER",
    "DELETE_FAVORITE",
    "DELETE_FOSTER",
    "DELETE_RESCUE",
    "DELETE_USER",
    "DELETE_VETERINARIAN",
    "LOGIN",
    "SHOW_ADOPTER_DETAILS",
    "SHOW_ADOPTERS",
    "SHOW_FAVORITES",
    "SHOW_FORMS",
    "SHOW_FOSTER_DETAILS",
    "SHOW_FOSTERS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
    "SHOW_USER_DETAILS",
    "SHOW_USERS",
    "SHOW_VETERINARIAN_DETAILS",
    "SHOW_VETERINARIANS",
  ],
  CANIDATE_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITES",
    "SHOW_FORMS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
  FOSTER_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "ADD_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITES",
    "SHOW_FORMS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
  MEMBER_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITES",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
  VET_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "ADD_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITES",
    "SHOW_FORMS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
};

module.exports.ADD_FAVORITE_RESCUE = "ADD_FAVORITE_RESCUE";
module.exports.ADD_RESCUE = "ADD_RESCUE";
module.exports.ADD_PET = "ADD_PET";
module.exports.DELETE_ADOPTER = "DELETE_ADOPTER";
module.exports.DELETE_FAVORITE = "DELETE_FAVORITE";
module.exports.DELETE_FOSTER = "DELETE_FOSTER";
module.exports.DELETE_RESCUE = "DELETE_RESCUE";
module.exports.DELETE_USER = "DELETE_USER";
module.exports.DELETE_VETERINARIAN = "DELETE_VETERINARIAN";
module.exports.LOGIN = "LOGIN";
module.exports.SHOW_ADOPTER_DETAILS = "SHOW_ADOPTER_DETAILS";
module.exports.SHOW_ADOPTERS = "SHOW_ADOPTERS";
module.exports.SHOW_FAVORITES = "SHOW_FAVORITES";
module.exports.SHOW_FOSTER_DETAILS = "SHOW_FOSTER_DETAILS";
module.exports.SHOW_FOSTERS = "SHOW_FOSTERS";
module.exports.SHOW_RESCUE_DETAILS = "SHOW_RESCUE_DETAILS";
module.exports.SHOW_RESCUES = "SHOW_RESCUES";
module.exports.SHOW_USER_DETAILS = "SHOW_USER_DETAILS";
module.exports.SHOW_USERS = "SHOW_USERS";
module.exports.SHOW_VETERINARIAN_DETAILS = "SHOW_VETERINARIAN_DETAILS";
module.exports.SHOW_VETERINARIANS = "SHOW_VETERINARIANS";