module.exports.JWT_OPTIONS = {
  ADMIN_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "ADD_RESCUE",
    "ADD_PET",
    "DELETE_FAVORITE",
    "DELETE_RESCUE",
    "LOGIN",
    "SHOW_ADOPTERS",
    "SHOW_FAVORITE",
    "SHOW_FORMS",
    "SHOW_FOSTERS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
    "SHOW_USERS",
    "SHOW_VETS",
  ],
  CANIDATE_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITE",
    "SHOW_FORMS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
  FOSTER_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "ADD_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITE",
    "SHOW_FORMS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
  MEMBER_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITE",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
  VET_AUDIENCE: [
    "ADD_FAVORITE_RESCUE",
    "ADD_RESCUE",
    "DELETE_FAVORITE",
    "LOGIN",
    "SHOW_FAVORITE",
    "SHOW_FORMS",
    "SHOW_RESCUE_DETAILS",
    "SHOW_RESCUES",
  ],
};

module.exports.ADD_FAVORITE_RESCUE = "ADD_FAVORITE_RESCUE";
module.exports.ADD_RESCUE = "ADD_RESCUE";
module.exports.ADD_PET = "ADD_PET";
module.exports.DELETE_FAVORITE = "DELETE_FAVORITE";
module.exports.DELETE_RESCUE = "DELETE_RESCUE";
module.exports.LOGIN = "LOGIN";
module.exports.SHOW_RESCUE_DETAILS = "SHOW_RESCUE_DETAILS";
module.exports.SHOW_USERS = "SHOW_USERS";