import React from "react";
import AdminCard from "../AdminCard";

export const adminProps = [
  {
    id: "3a1d7e28-e65d-4f4e-bf4f-85aa7d13e99c",
    username: "admin",
    name: "Amanda Smith",
    displayName: "Amanda",
    firstName: "Amanda",
    lastName: "Smith",
    email: "admin@example.com",
    numCurrentRescues: 5,
    numTotalRescues: 70,
    numHouseholdPets: 3,
    numHouseholdPeople: 2,
    favorite: ["1", "2", "3"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "placeholder-users",
    bio: "Hello, I'm proud to serve as an administrator at a puppy and kitten adoption and rescue agency. Working in an environment where I get to witness the joy of animals finding their forever homes brings me immense fulfillment. From coordinating adoption events to managing paperwork and logistics, I'm dedicated to ensuring that every puppy and kitten in our care finds a loving family to call their own.\n\nMy passion for puppies and kittens runs deep, and I'm constantly inspired by their resilience and capacity for love. Whether it's cuddling with a litter of kittens or playing fetch with energetic puppies, I cherish every moment spent with these adorable creatures. I firmly believe in the power of pet adoption and the positive impact it has on both animals and their adoptive families.\n\nIn my role, I strive to streamline our adoption process, making it as smooth and stress-free as possible for both our furry friends and potential adopters. I take pride in creating a welcoming and supportive environment where everyone feels valued and appreciated. Seeing the wagging tails and purring cuddles of our adopted pets reminds me every day why I'm passionate about what I do.\n\nOutside of work, you can often find me volunteering at local animal shelters or fostering puppies and kittens in need of temporary care. I'm committed to making a difference in the lives of animals, one adoption at a time.",
  },
  {
    id: "2",
    username: "Ethan",
    name: "Ethan Mitchell",
    displayName: "Mitchell Family",
    firstName: "Ethan",
    lastName: "Mitchell",
    email: "mitchell@example.com",
    numCurrentRescues: 1,
    numTotalRescues: 8,
    numHouseholdPets: 1,
    numHouseholdPeople: 2,
    favorite: ["1", "2", "3", "4", "5"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "2",
    bio: "",
  },
  {
    id: "3",
    username: "Sophia",
    name: "Sophia Johnson",
    displayName: "Sophia",
    firstName: "Sophia",
    lastName: "Johnson",
    email: "Johnson@example.com",
    numCurrentRescues: 0,
    numTotalRescues: 3,
    numHouseholdPets: 5,
    numHouseholdPeople: 1,
    favorite: ["2"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "23",
    bio: "",
  },
  {
    id: "4",
    username: "Olivia",
    name: "Olivia Brown",
    displayName: "Olivia",
    firstName: "Olivia",
    lastName: "Brown",
    email: "test@example.com",
    numCurrentRescues: 0,
    numTotalRescues: 16,
    numHouseholdPets: 2,
    numHouseholdPeople: 5,
    favorite: [],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "21",
    bio: "",
  },
  {
    id: "5",
    username: "Noah",
    name: "Noah Wilson",
    displayName: "Noah",
    firstName: "Noah",
    lastName: "Wilson",
    email: "noah@example.com",
    numCurrentRescues: 2,
    numTotalRescues: 12,
    numHouseholdPets: 3,
    numHouseholdPeople: 4,
    favorite: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "44",
    bio: "",
  },
  {
    id: "6",
    username: "Liam",
    name: "Liam Anderson",
    displayName: "Liam",
    firstName: "Liam",
    lastName: "Anderson",
    email: "liam@email.com",
    numCurrentRescues: 1,
    numTotalRescues: 6,
    numHouseholdPets: 2,
    numHouseholdPeople: 3,
    favorite: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "54",
    bio: "",
  },
  {
    id: "7",
    username: "Emma",
    name: "Emma Thomas",
    displayName: "Emma",
    firstName: "Emma",
    lastName: "Thomas",
    email: "emma@example.com",
    numCurrentRescues: 0,
    numTotalRescues: 4,
    numHouseholdPets: 1,
    numHouseholdPeople: 2,
    favorite: [],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "40",
    bio: "",
  },
  {
    id: "8",
    username: "Aiden",
    name: "Aiden White",
    displayName: "Aiden",
    firstName: "Aiden",
    lastName: "White",
    email: "ava@example.com",
    numCurrentRescues: 1,
    numTotalRescues: 2,
    numHouseholdPets: 3,
    numHouseholdPeople: 2,
    favorite: ["1", "2", "3", "4"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "6",
    bio: "",
  },
  {
    id: "9",
    username: "Ava",
    name: "Ava Martinez",
    displayName: "Ava",
    firstName: "Ava",
    lastName: "Martinez",
    email: "martinez@email.com",
    numCurrentRescues: 0,
    numTotalRescues: 1,
    numHouseholdPets: 2,
    numHouseholdPeople: 3,
    favorite: ["1", "2", "3"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "25",
    bio: "",
  },
  {
    id: "10",
    username: "Mia",
    name: "Mia Garcia",
    displayName: "Mia",
    firstName: "Mia",
    lastName: "Garcia",
    email: "garcia@email.com",
    numCurrentRescues: 0,
    numTotalRescues: 5,
    numHouseholdPets: 1,
    numHouseholdPeople: 2,
    favorite: ["1"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "22",
    bio: "",
  },
  {
    id: "11",
    username: "Lucas",
    name: "Lucas Dubois",
    displayName: "Lucas",
    firstName: "Lucas",
    lastName: "Dubois",
    email: "lucas@example.com",
    numCurrentRescues: 0,
    numTotalRescues: 23,
    numHouseholdPets: 2,
    numHouseholdPeople: 4,
    favorite: ["1", "2"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "57",
    bio: "",
  },
  {
    id: "12",
    username: "Isabella",
    name: "Isabella Johnson",
    displayName: "Isabella",
    firstName: "Isabella",
    lastName: "Johnson",
    email: "ij@email.com",
    numCurrentRescues: 0,
    numTotalRescues: 0,
    numHouseholdPets: 1,
    numHouseholdPeople: 2,
    favorite: ["1", "2", "3"],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "31",
    bio: "",
  },
  {
    id: "13",
    username: "William",
    name: "William Brown",
    displayName: "William",
    firstName: "William",
    lastName: "Brown",
    email: "brown@email.com",
    numCurrentRescues: 8,
    numTotalRescues: 53,
    numHouseholdPets: 2,
    numHouseholdPeople: 2,
    favorite: [],
    type: "Admin",
    role: "admin",
    hasBackgroundCheck: true,
    image: "9",
    bio: "",
  },
];

export function getAdminCards() {
  return adminProps.map((admin) => (
    <AdminCard
      key={admin.id}
      id={admin.id}
      username={admin.username}
      name={admin.name}
      displayName={admin.displayName}
      firstName={admin.firstName}
      lastName={admin.lastName}
      email={admin.email}
      numCurrentRescues={admin.numCurrentRescues}
      numTotalRescues={admin.numTotalRescues}
      numHouseholdPets={admin.numHouseholdPets}
      numHouseholdPeople={admin.numHouseholdPeople}
      favorite={admin.favorite}
      type={admin.type}
      role={admin.role}
      hasBackgroundCheck={admin.hasBackgroundCheck}
      image={admin.image}
      bio={admin.bio}
    />
  ));
}
