name: Playwright Visual Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1-5" # Run this workflow at 5 AM every weekday

jobs:
  playwright-visual-tests:
    name: Run Playwright Visual Tests
    timeout-minutes: 120
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install development dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Print Playwright version
        run: npx playwright --version

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
