name: Jest Unit Tests and Code Coverage

on:
  workflow_call:

jobs:
  jest-unit-tests:
    name: Jest Unit Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      DESTINATION_DIR_FOR_PAGES: ${{ github.ref_name }}/${{ (github.event_name == 'push' || github.event_name == 'pull_request') && format('commits/{0}', github.sha) || format('runs/{0}', github.run_id) }}/unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests with Code Coverage
        run: npm run test:all:coverage:ci 2>&1 | tee jest-unit-test-results.txt

      - name: Upload Jest coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/

      - name: Deploy Code Coverage Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage
          destination_dir: ${{ env.DESTINATION_DIR_FOR_PAGES }}

      - name: Set Test Results Summary as env variable
        run: |
          results=$(grep -A5 "Test Suites:" < jest-unit-test-results.txt | sed ':a;N;$!ba;s/\n/__NEWLINE__/g')
          short_sha=$(echo "${{ github.sha }}" | cut -c 1-8)
          repo="https://github.com/${{ github.repository }}"
          commit_url="$repo/commit/${{ github.sha }}"
          workflow_url="$repo/actions/runs/${{ github.run_id }}"
          echo "TEST_RESULTS_SUMMARY=<div style='margin: 50px; padding-left: 20px; border: 1px solid black;'><h1>Jest Unit Test Results</h1><h4>$results</h4><h3><a href='https://${{ github.repository_owner }}.github.io/Puppies-and-Kittens-Adoption-Agency/${{ env.DESTINATION_DIR_FOR_PAGES }}/lcov-report'>View Code Coverage Report</a></h3><h4>Latest Commit <a href='$commit_url'>$short_sha</a><br>By ${{ github.actor }}<br>Branch <a href='$repo'>${{ github.ref_name }}</a><br>Workflow <a href='$workflow_url'>${{ github.workflow }}</a><br>Tests completed $(date)</h4></div>" | sed 's/__NEWLINE__/<br>/g' >> "$GITHUB_ENV"

      - name: Display Test Results Summary in GitHub Step Summary
        run: echo "${{ env.TEST_RESULTS_SUMMARY }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Write Test Results Summary to HTML file
        run: |
          mkdir -p test-results-summary
          wget -O test-results-summary/old-Test-Summary.html https://${{ github.repository_owner }}.github.io/Puppies-and-Kittens-Adoption-Agency/test-results-summary/Test-Summary.html || true
          echo "${{ env.TEST_RESULTS_SUMMARY }}" > test-results-summary/Test-Summary.html
          cat test-results-summary/old-Test-Summary.html >> test-results-summary/Test-Summary.html

      - name: Deploy Test Results Summary to homepage on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: test-results-summary
          destination_dir: test-results-summary
