name: Jest Unit Tests and Code Coverage

on:
  workflow_call:

jobs:
  jest-unit-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:all:coverage:ci

      - name: Upload Jest coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
