name: Jest Unit Tests and Code Coverage

on:
  workflow_call:

jobs:
  jest-unit-tests:
    name: Jest Unit Tests
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test:all:coverage:ci -- --json --outputFile=jest-results.json

      - name: Set test results output
        id: test-results
        run: |
          results=$(grep -E 'Test Suites|Tests|Snapshots|Time|Ran all test suites' jest-results.json)
          echo "results=$results" >> $GITHUB_ENV

      - name: Upload Jest coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Create job summary
        run: echo "::notice file=jest-results.json::${{ env.results }}"
