name: Manual Automated Checks

on:
  # checkov:skip=CKV_GHA_7
  workflow_dispatch:
    inputs:
      prettier:
        description: "Run Prettier"
        type: boolean
        default: true
      super-linter:
        description: "Run Super-Linter"
        type: boolean
        default: true
      jest-unit-tests:
        description: "Run Jest Unit Tests"
        type: boolean
        default: true
      playwright-visual-tests:
        description: "Run Playwright Visual Tests"
        type: boolean
        default: true
      playwright-lighthouse-tests:
        description: "Run Playwright Lighthouse Audit Tests"
        type: boolean
        default: true
      merge-playwright-visual-reports:
        description: "Run Merge Playwright Reports"
        type: boolean
        default: true
      slack-notification:
        description: "Run Slack Notification"
        type: boolean
        default: true

env:
  ALGORITHM: ${{ vars.ALGORITHM }}
  EXPIRY: ${{ vars.EXPIRY }}
  ISSUER: ${{ vars.ISSUER }}
  REACT_APP_ENV: ${{ vars.REACT_APP_ENV }}
  SECRET: ${{ secrets.SECRET }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TEST_ENV: ${{ vars.TEST_ENV }}
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  TEST_USERNAME: ${{ secrets.TEST_USERNAME }}

jobs:
  run-prettier:
    name: Formatting
    if: github.event.inputs.prettier == 'true'
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/prettier.yml@main

  run-super-linter:
    name: Linters
    if: github.event.inputs.super-linter == 'true'
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/super-linter.yml@main

  run-jest-unit-tests:
    name: Unit Tests
    if: github.event.inputs.jest-unit-tests == 'true'
    permissions:
      contents: write
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/jest-unit-tests.yml@main

  run-playwright-visual-tests:
    name: Playwright Tests
    if: github.event.inputs.playwright-visual-tests == 'true'
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/playwright-visual-tests.yml@main
    secrets: inherit

  run-playwright-lighthouse-tests:
    name: Playwright Tests
    needs: [run-jest-unit-tests]
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/playwright-lighthouse-tests.yml@main
    secrets: inherit

  run-merge-playwright-visual-reports:
    name: Merge Reports
    if: always() && needs.run-playwright-visual-tests.result != 'skipped' && needs.run-playwright-visual-tests.result != 'cancelled' && needs.run-playwright-lighthouse-tests.result != 'skipped' && needs.run-playwright-lighthouse-tests.result != 'cancelled' && github.event.inputs.merge-playwright-visual-reports == 'true'
    needs: [run-playwright-visual-tests, run-playwright-lighthouse-tests]
    permissions:
      contents: write
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/merge-playwright-visual-reports.yml@main

  slack-notification:
    name: Notifications
    if: always() && needs.run-merge-playwright-visual-reports.result != 'cancelled' && github.event.inputs.slack-notification == 'true'
    needs:
      [
        run-prettier,
        run-super-linter,
        run-jest-unit-tests,
        run-playwright-visual-tests,
        run-merge-playwright-visual-reports,
      ]
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/slack-notification.yml@main
    secrets: inherit
