name: Merge Visual Reports

on:
  workflow_call:

jobs:
  merge-playwright-visual-reports:
    name: Merge Visual Reports
    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      DESTINATION_DIR_FOR_PAGES: ${{ github.ref_name }}/${{ (github.event_name == 'push' || github.event_name == 'pull_request') && format('commits/{0}', github.sha) || format('runs/{0}', github.run_id) }}/visual-tests-report

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install development dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: npm ci
        working-directory: playwright

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: playwright/all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./all-blob-reports
        working-directory: playwright

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-visual-html-report
          path: playwright/playwright-report/
          retention-days: 30

      - name: Deploy Merged Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright/playwright-report/
          destination_dir: ${{ env.DESTINATION_DIR_FOR_PAGES }}

      - name: Download lighthouse audit reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          path: playwright/all-lighthouse-reports
          pattern: lighthouse-audit-report-*
          merge-multiple: true

      - name: Deploy Lighthouse Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright/all-lighthouse-reports
          destination_dir: playwright/lighthouse-audit-reports

      - name: Set Test Results Summary as env variable
        run: 'echo "TEST_RESULTS_SUMMARY=<div style=''margin: 50px; padding: 20px; border: 1px solid black;''><h1>Playwright Visual Test Results</h1><h3><a href=''https://${{ github.repository_owner }}.github.io/Puppies-and-Kittens-Adoption-Agency/${{ env.DESTINATION_DIR_FOR_PAGES }}''>View Visual Test Report</a></h3><p>Tests ran $(date)</p><p>By: ${{ github.actor }}</p><p>Branch: ${{ github.ref_name }}</p><p>Event: ${{ github.event_name }}</p></div>" >> "$GITHUB_ENV"'

      - name: Display Test Results Summary in GitHub Step Summary
        run: echo "${{ env.TEST_RESULTS_SUMMARY }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Write Test Results Summary to HTML file
        run: |
          mkdir -p test-results-summary
          wget -O test-results-summary/old-Test-Summary.html https://${{ github.repository_owner }}.github.io/Puppies-and-Kittens-Adoption-Agency/test-results-summary/Test-Summary.html || true
          echo "${{ env.TEST_RESULTS_SUMMARY }}" > test-results-summary/Test-Summary.html
          cat test-results-summary/old-Test-Summary.html >> test-results-summary/Test-Summary.html

      - name: Deploy Test Results Summary to homepage on GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: test-results-summary
          destination_dir: test-results-summary
