name: Lighthouse Tests

on:
  workflow_call:

jobs:
  playwright-visual-tests:
    name: Lighthouse Tests
    timeout-minutes: 60
    # Running on windows because the OS matters for performance testing comparisons.
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install development dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: npm ci
        working-directory: playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: playwright

      - name: Print Playwright version
        run: npx playwright --version
        working-directory: playwright

      - name: Run Playwright tests
        run: npm run lighthouse:ci ${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
        working-directory: playwright
        env:
          REACT_APP_ENV: ${{ vars.REACT_APP_ENV }}
          ALGORITHM: ${{ vars.ALGORITHM }}
          EXPIRY: ${{ vars.EXPIRY }}
          ISSUER: ${{ vars.ISSUER }}
          SECRET: ${{ secrets.SECRET }}
          TEST_ENV: ${{ vars.TEST_ENV }}
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

      - name: Upload Playwright blob reports to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: blob-report-lighthouse-${{ matrix.shardIndex }}
          path: playwright/blob-report/lighthouse
          retention-days: 1

      - name: Upload Lighthouse Audit reports to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-audit-report-${{ matrix.shardIndex }}
          path: playwright/lighthouse-audit-reports
          retention-days: 15
