name: Playwright Visual Tests

on:
  workflow_run:
    workflows: ["Formatters and Linters Checks"]
    types:
      - completed

jobs:
  playwright-visual-tests:
    name: Playwright Visual Tests
    timeout-minutes: 60
    # Running on windows because the OS matters for visual testing comparisons.
    runs-on: windows-latest
    # Only run if the Formatters and Linters Checks workflow has completed successfully.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install development dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: npm ci
        working-directory: playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: playwright

      - name: Print Playwright version
        run: npx playwright --version
        working-directory: playwright

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: playwright

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30
