name: Scheduled Automated Checks

on:
  # Run this workflow at 12 PM UTC (which is 5 AM MST) every weekday. Doesn't account for daylight saving time.
  schedule:
    - cron: "0 12 * * 1-5"

env:
  ALGORITHM: ${{ vars.ALGORITHM }}
  EXPIRY: ${{ vars.EXPIRY }}
  ISSUER: ${{ vars.ISSUER }}
  REACT_APP_ENV: ${{ vars.REACT_APP_ENV }}
  SECRET: ${{ secrets.SECRET }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TEST_ENV: ${{ vars.TEST_ENV }}
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  TEST_USERNAME: ${{ secrets.TEST_USERNAME }}

jobs:
  run-prettier:
    name: Formatting
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/prettier.yml@main

  run-super-linter:
    name: Linters
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/super-linter.yml@main

  run-codeql:
    name: Security Analysis
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/codeql.yml@main

  # run-jest-unit-tests:
  #   name: Unit Tests
  #   needs: [run-prettier, run-super-linter]
  #   permissions:
  #     contents: write
  #   uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/jest-unit-tests.yml@main

  run-playwright-visual-tests:
    name: Playwright Tests
    needs: [run-prettier, run-super-linter, run-codeql]
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/playwright-visual-tests.yml@main
    secrets: inherit

  run-merge-playwright-visual-reports:
    name: Playwright Tests
    if: always() && needs.run-playwright-visual-tests.result != 'skipped' && needs.run-playwright-visual-tests.result != 'cancelled'
    needs: [run-playwright-visual-tests]
    permissions:
      contents: write
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/merge-playwright-visual-reports.yml@main

  run-playwright-lighthouse-tests:
    name: Playwright Tests
    needs: [run-playwright-visual-tests]
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/playwright-lighthouse-tests.yml@main
    secrets: inherit

  run-merge-playwright-lighthouse-reports:
    name: Playwright Tests
    if: always() && needs.run-playwright-lighthouse-tests.result != 'skipped' && needs.run-playwright-lighthouse-tests.result != 'cancelled'
    needs: [run-playwright-lighthouse-tests]
    permissions:
      contents: write
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/merge-playwright-lighthouse-reports.yml@main

  slack-notification:
    name: Notifications
    if: always() && needs.run-merge-playwright-lighthouse-reports.result != 'cancelled'
    needs:
      [
        run-merge-playwright-visual-reports,
        run-merge-playwright-lighthouse-reports,
      ]
    uses: AcceleratingAutomation/Puppies-and-Kittens-Adoption-Agency/.github/workflows/slack-notification.yml@main
    secrets: inherit
