name: Send Slack Notification

on:
  workflow_call:

jobs:
  slack-notification:
    name: Slack Notification
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so we can compare

      - name: Get commit details
        id: get_commits
        uses: actions/github-script@v7
        with:
          script: |
            const { data: commits } = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 10
            });
            const commitDetails = commits.map(commit => {
              const shortSha = commit.sha.substring(0, 8);
              const commitUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/commit/${commit.sha}`;
              return `<${commitUrl}|${shortSha}> ${commit.commit.message} by ${commit.commit.author.name}`;
            }).join(' - ');
            return commitDetails;

      - name: Get job statuses
        id: get_job_statuses
        uses: actions/github-script@v7
        with:
          script: |
            const runId = context.runId;
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            const jobStatuses = jobs.jobs.filter(job => job.name !== 'Notifications / Slack Notification').map(job => {
              const jobName = job.name.split('/')[1];
              const status = job.conclusion || job.status;
              const emoji = status === 'success' ? ':white_check_mark:' : (status === 'failure' ? ':x:' : ':warning:');
              return `${emoji} *${jobName}:* ${status}`;
            });
            return jobStatuses.join(' - ');

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          text: |
            *Job Statuses:*
            ${{ steps.get_job_statuses.outputs.result }}
            *Slack Notification:* ${{ job.status }} :white_check_mark:

            *Last 10 Commits:*
            ${{ steps.get_commits.outputs.result }}

            Additional details for last commit:
          status: ${{ job.status }}
          fields: repo,message,commit,author,eventName,ref,workflow,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
