name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  automated-checks:
    timeout-minutes: 10
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Print Prettier version
        run: npx prettier --version

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Print ESLint version
        run: npx eslint --version

      - name: Run ESLint
        run: npx eslint .

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Print Playwright version
        run: npx playwright --version

      # Only upload playwright-report if tests ran
      - name: Set output variable
        id: vars
        run: echo "::set-output name=playwright-tests-ran::true"

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: steps.vars.outputs.playwright-tests-ran == 'true'
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
