name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  setup:
    timeout-minutes: 10
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - name: Print Prettier version
        run: npx prettier --version

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Print Playwright version
        run: npx playwright --version

      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
