name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  setup:
    timeout-minutes: 10
    runs-on: windows-latest
    # The timestamp output is used to ensure that the setup job always runs and is not skipped due to caching.
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
      node_version: ${{ steps.get_node_version.outputs.node_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Archive code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - id: get_node_version
        run: echo "::set-output name=node_version::$(node --version)"

      - id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

  prettier:
    timeout-minutes: 10
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code

      - name: Print Node.js version
        env:
          NODE_VERSION: ${{ needs.setup.outputs.node_version }}
        run: echo $NODE_VERSION

      - name: Install dependencies
        run: npm ci

      - name: Print Prettier version
        run: npx prettier --version

      - name: Run Prettier check
        run: npx prettier --check .

  playwright:
    timeout-minutes: 60
    needs: [setup, prettier]
    runs-on: windows-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: code

      - name: Print Node.js version
        env:
            NODE_VERSION: ${{ needs.setup.outputs.node_version }}
        run: echo $NODE_VERSION

      - name: Install dependencies
        run: npm ci

      - name: Print Playwright version
        run: npx playwright --version

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
