name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  setup:
    timeout-minutes: 10
    runs-on: windows-latest
    # The timestamp output is used to ensure that the setup job always runs and is not skipped due to caching.
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Print Node.js version
        run: node --version

      - name: Install dependencies
        run: npm ci

      - id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

  prettier:
    timeout-minutes: 10
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Print Prettier version
        run: npx prettier --version

      - name: Run Prettier check
        run: npx prettier --check .

  playwright:
    timeout-minutes: 60
    needs: prettier
    runs-on: windows-latest
    steps:
      - name: Print Playwright version
        run: npx playwright --version

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
