name: Report Results On GitHub Pages

on:
  workflow_call:

jobs:
  upload-playwright-report-to-pages:
    name: Report Results On GitHub Pages
    timeout-minutes: 10
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy Merged Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright/playwright-report/${{ github.ref_name }}/${{ github.sha }}
